export const operationalTeamProfiles = {
  en: [
    {
      id: 'OPS-01',
      group: 'management',
      category: 'Head of SPPG (1 person)',
      icon: 'SPPG',
      description: 'Overall operational lead for the SPPG Soe unit.',
      members: [
        {
          id: 'OPS-M01',
          name: 'Drs. Yohanes Kofi, M.Si.',
          position: 'Head of SPPG',
          role: 'Operational leadership & cross-team coordination',
          email: 'kepala.sppg@ffi-soe.org',
          phone: '+62-821-0000-0001',
          location: 'Soe, South Central Timor',
          bio: 'Coordinates daily service delivery, safety compliance, and performance reporting across the operational teams.',
          specialties: ['Operational Leadership', 'Service Quality', 'Stakeholder Coordination'],
          experience: '12 years in public nutrition operations',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-02',
      group: 'management',
      category: 'Nutritionist (1 person)',
      icon: 'GIZI',
      description: 'Nutrition planning and monitoring.',
      members: [
        {
          id: 'OPS-M02',
          name: 'Natalia Benu, S.Gz.',
          position: 'Nutritionist',
          role: 'Meal planning & nutrition monitoring',
          email: 'gizi@ffi-soe.org',
          phone: '+62-821-0000-0002',
          location: 'Soe, South Central Timor',
          bio: 'Designs balanced menus and monitors nutrition adequacy for 2,900 beneficiaries.',
          specialties: ['Menu Planning', 'Nutrition Assessment', 'Food Safety'],
          experience: '9 years in community nutrition',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-03',
      group: 'management',
      category: 'Accounting & HR (1 person)',
      icon: 'FIN',
      description: 'Financial control and personnel administration.',
      members: [
        {
          id: 'OPS-M03',
          name: 'Rika Lomi, S.E.',
          position: 'Accountant & HR',
          role: 'Budget control, payroll, and personnel',
          email: 'keuangan.hr@ffi-soe.org',
          phone: '+62-821-0000-0003',
          location: 'Soe, South Central Timor',
          bio: 'Handles budgeting, payroll, and compliance for the operational workforce.',
          specialties: ['Budgeting', 'Payroll', 'HR Administration'],
          experience: '10 years in nonprofit finance',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-04',
      group: 'management',
      category: 'Chef (1 person)',
      icon: 'COOK',
      description: 'Leads the hot kitchen production line.',
      members: [
        {
          id: 'OPS-M04',
          name: 'Paulus Reta, A.Md.Kul.',
          position: 'Chef',
          role: 'Kitchen leadership & quality control',
          email: 'leader.cook@ffi-soe.org',
          phone: '+62-821-0000-0004',
          location: 'Soe, South Central Timor',
          bio: 'Leads cooking workflow to hit daily output targets with consistent taste and safety.',
          specialties: ['Kitchen Operations', 'Recipe Standardization', 'Food Safety'],
          experience: '11 years in large-scale cooking',
          kitchenProfile: {
            operationalSince: '2019-03-15',
            operationalYears: 6,
            totalDailyMeals: 1750,
            mealsPerSchool: { average: 437, min: 280, max: 620 },
            staffBreakdown: {
              executive: { chef: 1 },
              supervisory: { souChef: 1, kitchenManager: 1 },
              production: {
                headCook: 2,
                cooks: 8,
                prepWorkers: 12,
                dishwashers: 4,
                cleaners: 3,
              },
              support: { drivers: 4, storageManager: 1 },
            },
            totalStaff: 37,
            operatingDays: 240,
            operatingHours: '06:00 - 14:00',
            equipmentCount: 28,
            storageCapacity: '15 tons',
            wasteReduction: '94%',
            foodSafetyCertification: 'HACCP Certified',
            localSourcePercentage: 88,
          },
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-05',
      group: 'management',
      category: 'Animal Protein Cook (1 person)',
      icon: 'PROT',
      description: 'Prepares animal protein dishes for daily menus.',
      members: [
        {
          id: 'OPS-M05',
          name: 'Anton Nope, A.Md.TP.',
          position: 'Animal Protein Cook',
          role: 'Protein preparation & portion consistency',
          email: 'cook.hewani@ffi-soe.org',
          phone: '+62-821-0000-0005',
          location: 'Soe, South Central Timor',
          bio: 'Prepares animal protein dishes for 1,750 daily meals with strict temperature control.',
          specialties: ['Protein Processing', 'Temperature Control', 'Hygiene'],
          experience: '8 years in protein prep',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-06',
      group: 'management',
      category: 'Vegetable Cooks (2 people)',
      icon: 'VEG',
      description: 'Vegetable preparation and cooking.',
      members: [
        {
          id: 'OPS-M06',
          name: 'Lina Kefi, A.Md.Kul.',
          position: 'Vegetable Cook Coordinator',
          role: 'Vegetable prep coordination for 2-person team',
          email: 'cook.sayur@ffi-soe.org',
          phone: '+62-821-0000-0006',
          location: 'Soe, South Central Timor',
          bio: 'Coordinates vegetable prep to maintain nutrition and texture across large batches.',
          specialties: ['Vegetable Prep', 'Batch Cooking', 'Nutrition Retention'],
          experience: '7 years in vegetable cooking',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-07',
      group: 'management',
      category: 'Rice Cook (1 person)',
      icon: 'RICE',
      description: 'Rice production and holding.',
      members: [
        {
          id: 'OPS-M07',
          name: 'Maria Oetpah, A.Md.Kul.',
          position: 'Rice Cook',
          role: 'Rice production & holding management',
          email: 'cook.nasi@ffi-soe.org',
          phone: '+62-821-0000-0007',
          location: 'Soe, South Central Timor',
          bio: 'Ensures consistent rice quality and safe holding for distribution.',
          specialties: ['Rice Production', 'Holding Procedures', 'Batch Timing'],
          experience: '9 years in staple cooking',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-08',
      group: 'operational',
      category: 'Cook Helpers (2 people)',
      icon: 'HELP',
      description: 'Support for cooking stations.',
      members: [
        {
          id: 'OPS-M08',
          name: 'Dedi Fobia, A.Md.Kul.',
          position: 'Cook Helper Coordinator',
          role: 'Station support & prep assistance',
          email: 'helper.cook@ffi-soe.org',
          phone: '+62-821-0000-0008',
          location: 'Soe, South Central Timor',
          bio: 'Coordinates helper tasks to keep cooking flow on schedule.',
          specialties: ['Prep Support', 'Station Setup', 'Sanitation'],
          experience: '6 years in kitchen support',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-09',
      group: 'operational',
      category: 'Prep Leader (1 person)',
      icon: 'PREP',
      description: 'Supervises preparation activities.',
      members: [
        {
          id: 'OPS-M09',
          name: 'Yulianus Timo, A.Md.Kul.',
          position: 'Prep Leader',
          role: 'Prep workflow & task allocation',
          email: 'leader.persiapan@ffi-soe.org',
          phone: '+62-821-0000-0009',
          location: 'Soe, South Central Timor',
          bio: 'Leads preparation team of 9 to ensure ingredients are ready on time.',
          specialties: ['Prep Planning', 'Ingredient Handling', 'Team Coordination'],
          experience: '10 years in kitchen prep',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-10',
      group: 'operational',
      category: 'Warehouse (1 person)',
      icon: 'WARE',
      description: 'Storage and inventory control.',
      members: [
        {
          id: 'OPS-M10',
          name: 'Hendrik Benu, A.Md.Log.',
          position: 'Warehouse Officer',
          role: 'Inventory control & cold chain',
          email: 'gudang@ffi-soe.org',
          phone: '+62-821-0000-0010',
          location: 'Soe, South Central Timor',
          bio: 'Manages dry and cold storage using FIFO standards and daily stock checks.',
          specialties: ['Inventory Control', 'Cold Chain', 'Receiving'],
          experience: '8 years in warehouse operations',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-11',
      group: 'operational',
      category: 'Cleaning Service (2 people)',
      icon: 'CLEAN',
      description: 'Kitchen and facility sanitation.',
      members: [
        {
          id: 'OPS-M11',
          name: 'Roni Lake, A.Md.Kes.',
          position: 'Cleaning Service Coordinator',
          role: 'Sanitation routines & compliance',
          email: 'cleaning@ffi-soe.org',
          phone: '+62-821-0000-0011',
          location: 'Soe, South Central Timor',
          bio: 'Leads sanitation routines to maintain HACCP-level cleanliness.',
          specialties: ['Sanitation', 'Chemical Handling', 'Facility Care'],
          experience: '7 years in facility hygiene',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-12',
      group: 'operational',
      category: 'Technician (1 person)',
      icon: 'TECH',
      description: 'Equipment maintenance and troubleshooting.',
      members: [
        {
          id: 'OPS-M12',
          name: 'Sandro Mau, S.Kom.',
          position: 'Technician',
          role: 'Equipment maintenance & troubleshooting',
          email: 'teknisi@ffi-soe.org',
          phone: '+62-821-0000-0012',
          location: 'Soe, South Central Timor',
          bio: 'Maintains kitchen equipment and basic IT systems to prevent downtime.',
          specialties: ['Equipment Maintenance', 'Electrical Safety', 'IT Support'],
          experience: '8 years in technical support',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-13',
      group: 'operational',
      category: 'Prep Team (9 people)',
      icon: 'TEAM',
      description: 'Ingredient preparation team.',
      members: [
        {
          id: 'OPS-M13',
          name: 'Lydia Neno, A.Md.Kul.',
          position: 'Prep Team Coordinator',
          role: 'Coordinates 9-person prep team',
          email: 'tim.persiapan@ffi-soe.org',
          phone: '+62-821-0000-0013',
          location: 'Soe, South Central Timor',
          bio: 'Coordinates washing, cutting, and portioning of ingredients before cooking.',
          specialties: ['Ingredient Prep', 'Workflow Scheduling', 'Quality Checks'],
          experience: '6 years in food prep',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-14',
      group: 'operational',
      category: 'Portioning & Washing Leader (1 person)',
      icon: 'LEAD',
      description: 'Leads portioning and washing units.',
      members: [
        {
          id: 'OPS-M14',
          name: 'Bernadus Efi, A.Md.Kul.',
          position: 'Portioning & Washing Leader',
          role: 'Leads portioning (7) & washing (6) teams',
          email: 'leader.porsipencuci@ffi-soe.org',
          phone: '+62-821-0000-0014',
          location: 'Soe, South Central Timor',
          bio: 'Ensures accurate portions and clean utensils during peak production.',
          specialties: ['Portion Control', 'Workflow Balance', 'Hygiene Standards'],
          experience: '9 years in kitchen operations',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-15',
      group: 'operational',
      category: 'Portioning Team (7 people)',
      icon: 'PORT',
      description: 'Meal portioning team.',
      members: [
        {
          id: 'OPS-M15',
          name: 'Risma Nabu, A.Md.Kul.',
          position: 'Portioning Team Coordinator',
          role: 'Coordinates 7-person portioning line',
          email: 'tim.pemorsian@ffi-soe.org',
          phone: '+62-821-0000-0015',
          location: 'Soe, South Central Timor',
          bio: 'Maintains portion accuracy to meet nutritional targets.',
          specialties: ['Portion Accuracy', 'Speed & Flow', 'Packaging'],
          experience: '6 years in meal distribution',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-16',
      group: 'operational',
      category: 'Cookware & Dining Wash Team (6 people)',
      icon: 'WASH',
      description: 'Washing cookware and dining utensils.',
      members: [
        {
          id: 'OPS-M16',
          name: 'Dian Leu, A.Md.Kes.',
          position: 'Wash Team Coordinator',
          role: 'Leads 6-person wash team',
          email: 'tim.cuci@ffi-soe.org',
          phone: '+62-821-0000-0016',
          location: 'Soe, South Central Timor',
          bio: 'Manages washing and sanitizing of cookware and dining utensils.',
          specialties: ['Sanitation', 'Workflow Efficiency', 'Safety Procedures'],
          experience: '7 years in dishwashing operations',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-17',
      group: 'operational',
      category: 'Field Leader (1 person)',
      icon: 'FIELD',
      description: 'Distribution and field logistics lead.',
      members: [
        {
          id: 'OPS-M17',
          name: 'Julius Taolin, S.Sos.',
          position: 'Field Leader',
          role: 'Distribution control & on-site coordination',
          email: 'leader.lapangan@ffi-soe.org',
          phone: '+62-821-0000-0017',
          location: 'Soe, South Central Timor',
          bio: 'Coordinates delivery routes, handover, and field feedback.',
          specialties: ['Logistics', 'Route Planning', 'Stakeholder Liaison'],
          experience: '10 years in field operations',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-18',
      group: 'operational',
      category: 'Drivers (2 people)',
      icon: 'DRIVE',
      description: 'Meal delivery drivers.',
      members: [
        {
          id: 'OPS-M18',
          name: 'Edi Oematan, A.Md.Tra.',
          position: 'Driver Coordinator',
          role: 'Coordinates 2 delivery drivers',
          email: 'driver@ffi-soe.org',
          phone: '+62-821-0000-0018',
          location: 'Soe, South Central Timor',
          bio: 'Ensures safe and timely delivery across school routes.',
          specialties: ['Vehicle Operations', 'Safety Compliance', 'Route Timing'],
          experience: '9 years in transport',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-19',
      group: 'operational',
      category: 'Conductors (2 people)',
      icon: 'ROUTE',
      description: 'Route assistants for delivery and distribution.',
      members: [
        {
          id: 'OPS-M19',
          name: 'Mila Nule, A.Md.',
          position: 'Conductor Coordinator',
          role: 'Coordinates 2 route assistants',
          email: 'kondektur@ffi-soe.org',
          phone: '+62-821-0000-0019',
          location: 'Soe, South Central Timor',
          bio: 'Supports loading, unloading, and receipt documentation.',
          specialties: ['Loading Support', 'Documentation', 'Teamwork'],
          experience: '5 years in delivery support',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-20',
      group: 'operational',
      category: 'Field Team (1 person)',
      icon: 'TEAM',
      description: 'On-site support and reporting.',
      members: [
        {
          id: 'OPS-M20',
          name: 'Andri Kofi, S.Sos.',
          position: 'Field Team Coordinator',
          role: 'On-site support & reporting',
          email: 'tim.lapangan@ffi-soe.org',
          phone: '+62-821-0000-0020',
          location: 'Soe, South Central Timor',
          bio: 'Collects feedback and ensures smooth handover at schools.',
          specialties: ['On-site Coordination', 'Data Collection', 'Communication'],
          experience: '6 years in community outreach',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
  ],
  id: [
    {
      id: 'OPS-01',
      group: 'operational',
      category: 'Kepala SPPG (1 orang)',
      icon: 'SPPG',
      description: 'Pemimpin operasional utama untuk unit SPPG Soe.',
      members: [
        {
          id: 'OPS-M01',
          name: 'Drs. Yohanes Kofi, M.Si.',
          position: 'Kepala SPPG',
          role: 'Kepemimpinan operasional & koordinasi lintas tim',
          email: 'kepala.sppg@ffi-soe.org',
          phone: '+62-821-0000-0001',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Mengawal layanan harian, kepatuhan keamanan pangan, dan pelaporan kinerja tim.',
          specialties: ['Kepemimpinan Operasional', 'Mutu Layanan', 'Koordinasi Pemangku Kepentingan'],
          experience: '12 tahun di operasi gizi publik',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-02',
      group: 'operational',
      category: 'Ahli Gizi (1 orang)',
      icon: 'GIZI',
      description: 'Perencanaan dan pemantauan gizi.',
      members: [
        {
          id: 'OPS-M02',
          name: 'Natalia Benu, S.Gz.',
          position: 'Ahli Gizi',
          role: 'Perencanaan menu & pemantauan gizi',
          email: 'gizi@ffi-soe.org',
          phone: '+62-821-0000-0002',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Menyusun menu seimbang dan memantau kecukupan gizi untuk 2.900 penerima manfaat.',
          specialties: ['Perencanaan Menu', 'Asesmen Gizi', 'Keamanan Pangan'],
          experience: '9 tahun di gizi masyarakat',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-03',
      group: 'operational',
      category: 'Akuntan & Personalia (1 orang)',
      icon: 'FIN',
      description: 'Kontrol keuangan dan administrasi SDM.',
      members: [
        {
          id: 'OPS-M03',
          name: 'Rika Lomi, S.E.',
          position: 'Akuntan & Personalia',
          role: 'Kontrol anggaran, payroll, dan administrasi SDM',
          email: 'keuangan.hr@ffi-soe.org',
          phone: '+62-821-0000-0003',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Mengelola anggaran, payroll, dan kepatuhan administrasi SDM operasional.',
          specialties: ['Penganggaran', 'Payroll', 'Administrasi SDM'],
          experience: '10 tahun di keuangan nirlaba',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-04',
      group: 'management',
      category: 'Chef (1 orang)',
      icon: 'COOK',
      description: 'Memimpin lini produksi dapur panas.',
      members: [
        {
          id: 'OPS-M04',
          name: 'Paulus Reta, A.Md.Kul.',
          position: 'Chef',
          role: 'Kepemimpinan dapur & kontrol mutu',
          email: 'leader.cook@ffi-soe.org',
          phone: '+62-821-0000-0004',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Mengatur alur masak agar target harian tercapai dengan rasa dan keamanan yang konsisten.',
          specialties: ['Operasional Dapur', 'Standarisasi Resep', 'Keamanan Pangan'],
          experience: '11 tahun di masak skala besar',
          kitchenProfile: {
            operationalSince: '2019-03-15',
            operationalYears: 6,
            totalDailyMeals: 1750,
            mealsPerSchool: { average: 437, min: 280, max: 620 },
            staffBreakdown: {
              executive: { chef: 1 },
              supervisory: { souChef: 1, kitchenManager: 1 },
              production: {
                headCook: 2,
                cooks: 8,
                prepWorkers: 12,
                dishwashers: 4,
                cleaners: 3,
              },
              support: { drivers: 4, storageManager: 1 },
            },
            totalStaff: 37,
            operatingDays: 240,
            operatingHours: '06:00 - 14:00',
            equipmentCount: 28,
            storageCapacity: '15 ton',
            wasteReduction: '94%',
            foodSafetyCertification: 'Tersertifikasi HACCP',
            localSourcePercentage: 88,
          },
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-05',
      group: 'operational',
      category: 'Cook Hewani (1 orang)',
      icon: 'PROT',
      description: 'Menyiapkan menu protein hewani harian.',
      members: [
        {
          id: 'OPS-M05',
          name: 'Anton Nope, A.Md.TP.',
          position: 'Cook Hewani',
          role: 'Persiapan protein & konsistensi porsi',
          email: 'cook.hewani@ffi-soe.org',
          phone: '+62-821-0000-0005',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Menyiapkan menu protein hewani untuk 1.750 porsi harian dengan kontrol suhu ketat.',
          specialties: ['Pengolahan Protein', 'Kontrol Suhu', 'Higiene'],
          experience: '8 tahun di persiapan protein',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-06',
      group: 'operational',
      category: 'Cook Sayur (2 orang)',
      icon: 'VEG',
      description: 'Persiapan dan memasak sayuran.',
      members: [
        {
          id: 'OPS-M06',
          name: 'Lina Kefi, A.Md.Kul.',
          position: 'Koordinator Cook Sayur',
          role: 'Koordinasi masak sayur untuk tim 2 orang',
          email: 'cook.sayur@ffi-soe.org',
          phone: '+62-821-0000-0006',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Menjaga tekstur dan nilai gizi sayuran pada produksi dalam batch besar.',
          specialties: ['Persiapan Sayur', 'Masak Batch', 'Retensi Gizi'],
          experience: '7 tahun di masak sayur',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-07',
      group: 'operational',
      category: 'Cook Nasi (1 orang)',
      icon: 'RICE',
      description: 'Produksi dan penyimpanan nasi.',
      members: [
        {
          id: 'OPS-M07',
          name: 'Maria Oetpah, A.Md.Kul.',
          position: 'Cook Nasi',
          role: 'Produksi nasi & manajemen holding',
          email: 'cook.nasi@ffi-soe.org',
          phone: '+62-821-0000-0007',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Menjaga kualitas nasi dan prosedur penyimpanan aman sebelum distribusi.',
          specialties: ['Produksi Nasi', 'Prosedur Holding', 'Timing Batch'],
          experience: '9 tahun di masak makanan pokok',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-08',
      group: 'operational',
      category: 'Helper Cook (2 orang)',
      icon: 'HELP',
      description: 'Dukungan untuk stasiun memasak.',
      members: [
        {
          id: 'OPS-M08',
          name: 'Dedi Fobia, A.Md.Kul.',
          position: 'Koordinator Helper Cook',
          role: 'Dukungan stasiun & bantuan persiapan',
          email: 'helper.cook@ffi-soe.org',
          phone: '+62-821-0000-0008',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Mengatur tugas helper agar alur masak tetap sesuai jadwal.',
          specialties: ['Dukungan Prep', 'Setup Stasiun', 'Sanitasi'],
          experience: '6 tahun di dukungan dapur',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-09',
      group: 'operational',
      category: 'Leader Persiapan (1 orang)',
      icon: 'PREP',
      description: 'Mengawasi kegiatan persiapan bahan.',
      members: [
        {
          id: 'OPS-M09',
          name: 'Yulianus Timo, A.Md.Kul.',
          position: 'Leader Persiapan',
          role: 'Alur persiapan & pembagian tugas',
          email: 'leader.persiapan@ffi-soe.org',
          phone: '+62-821-0000-0009',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Memimpin tim persiapan 9 orang agar bahan siap tepat waktu.',
          specialties: ['Perencanaan Prep', 'Penanganan Bahan', 'Koordinasi Tim'],
          experience: '10 tahun di persiapan dapur',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-10',
      group: 'operational',
      category: 'Gudang (1 orang)',
      icon: 'WARE',
      description: 'Pengelolaan penyimpanan dan stok.',
      members: [
        {
          id: 'OPS-M10',
          name: 'Hendrik Benu, A.Md.Log.',
          position: 'Petugas Gudang',
          role: 'Kontrol stok & rantai dingin',
          email: 'gudang@ffi-soe.org',
          phone: '+62-821-0000-0010',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Mengelola penyimpanan kering dan dingin dengan standar FIFO dan cek stok harian.',
          specialties: ['Kontrol Persediaan', 'Rantai Dingin', 'Penerimaan Barang'],
          experience: '8 tahun di operasi gudang',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-11',
      group: 'operational',
      category: 'Cleaning Service (2 orang)',
      icon: 'CLEAN',
      description: 'Sanitasi dapur dan fasilitas.',
      members: [
        {
          id: 'OPS-M11',
          name: 'Roni Lake, A.Md.Kes.',
          position: 'Koordinator Cleaning Service',
          role: 'Rutin sanitasi & kepatuhan',
          email: 'cleaning@ffi-soe.org',
          phone: '+62-821-0000-0011',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Memimpin rutinitas kebersihan untuk menjaga standar HACCP.',
          specialties: ['Sanitasi', 'Penanganan Bahan Kimia', 'Perawatan Fasilitas'],
          experience: '7 tahun di kebersihan fasilitas',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-12',
      group: 'operational',
      category: 'Teknisi (1 orang)',
      icon: 'TECH',
      description: 'Perawatan peralatan dan troubleshooting.',
      members: [
        {
          id: 'OPS-M12',
          name: 'Sandro Mau, S.Kom.',
          position: 'Teknisi',
          role: 'Perawatan peralatan & troubleshooting',
          email: 'teknisi@ffi-soe.org',
          phone: '+62-821-0000-0012',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Merawat peralatan dapur dan sistem IT dasar agar operasional tidak terhenti.',
          specialties: ['Perawatan Peralatan', 'Keselamatan Listrik', 'Dukungan IT'],
          experience: '8 tahun di dukungan teknis',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-13',
      group: 'operational',
      category: 'Tim Persiapan (9 orang)',
      icon: 'TEAM',
      description: 'Tim persiapan bahan.',
      members: [
        {
          id: 'OPS-M13',
          name: 'Lydia Neno, A.Md.Kul.',
          position: 'Koordinator Tim Persiapan',
          role: 'Koordinasi tim persiapan 9 orang',
          email: 'tim.persiapan@ffi-soe.org',
          phone: '+62-821-0000-0013',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Mengatur pencucian, pemotongan, dan penimbangan bahan sebelum memasak.',
          specialties: ['Persiapan Bahan', 'Penjadwalan Alur', 'Pengecekan Mutu'],
          experience: '6 tahun di persiapan makanan',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-14',
      group: 'operational',
      category: 'Leader Pemorsian & Pencucian (1 orang)',
      icon: 'LEAD',
      description: 'Memimpin tim pemorsian dan pencucian.',
      members: [
        {
          id: 'OPS-M14',
          name: 'Bernadus Efi, A.Md.Kul.',
          position: 'Leader Pemorsian & Pencucian',
          role: 'Memimpin tim pemorsian (7) & pencucian (6)',
          email: 'leader.porsipencuci@ffi-soe.org',
          phone: '+62-821-0000-0014',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Menjaga akurasi porsi dan kebersihan alat saat produksi puncak.',
          specialties: ['Kontrol Porsi', 'Keseimbangan Alur', 'Standar Higiene'],
          experience: '9 tahun di operasi dapur',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-15',
      group: 'operational',
      category: 'Tim Pemorsian (7 orang)',
      icon: 'PORT',
      description: 'Tim pemorsian makanan.',
      members: [
        {
          id: 'OPS-M15',
          name: 'Risma Nabu, A.Md.Kul.',
          position: 'Koordinator Tim Pemorsian',
          role: 'Koordinasi lini pemorsian 7 orang',
          email: 'tim.pemorsian@ffi-soe.org',
          phone: '+62-821-0000-0015',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Menjaga akurasi porsi agar target gizi terpenuhi.',
          specialties: ['Akurasi Porsi', 'Kecepatan Alur', 'Pengemasan'],
          experience: '6 tahun di distribusi makanan',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-16',
      group: 'operational',
      category: 'Tim Cuci Alat Masak & Makan (6 orang)',
      icon: 'WASH',
      description: 'Pencucian alat masak dan alat makan.',
      members: [
        {
          id: 'OPS-M16',
          name: 'Dian Leu, A.Md.Kes.',
          position: 'Koordinator Tim Cuci',
          role: 'Memimpin tim cuci 6 orang',
          email: 'tim.cuci@ffi-soe.org',
          phone: '+62-821-0000-0016',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Mengelola pencucian dan sanitasi alat masak serta alat makan.',
          specialties: ['Sanitasi', 'Efisiensi Alur', 'Prosedur Keselamatan'],
          experience: '7 tahun di operasional pencucian',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-17',
      group: 'operational',
      category: 'Leader Lapangan (1 orang)',
      icon: 'FIELD',
      description: 'Pemimpin logistik dan distribusi lapangan.',
      members: [
        {
          id: 'OPS-M17',
          name: 'Julius Taolin, S.Sos.',
          position: 'Leader Lapangan',
          role: 'Kontrol distribusi & koordinasi di lapangan',
          email: 'leader.lapangan@ffi-soe.org',
          phone: '+62-821-0000-0017',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Mengatur rute pengantaran, serah terima, dan umpan balik dari lapangan.',
          specialties: ['Logistik', 'Perencanaan Rute', 'Liaison Pemangku Kepentingan'],
          experience: '10 tahun di operasi lapangan',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-18',
      group: 'operational',
      category: 'Driver (2 orang)',
      icon: 'DRIVE',
      description: 'Pengemudi distribusi makanan.',
      members: [
        {
          id: 'OPS-M18',
          name: 'Edi Oematan, A.Md.Tra.',
          position: 'Koordinator Driver',
          role: 'Koordinasi 2 driver distribusi',
          email: 'driver@ffi-soe.org',
          phone: '+62-821-0000-0018',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Menjaga keamanan dan ketepatan waktu pengantaran ke sekolah.',
          specialties: ['Operasi Kendaraan', 'Kepatuhan Keselamatan', 'Ketepatan Rute'],
          experience: '9 tahun di transportasi',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-19',
      group: 'operational',
      category: 'Kondektur (2 orang)',
      icon: 'ROUTE',
      description: 'Asisten rute untuk distribusi.',
      members: [
        {
          id: 'OPS-M19',
          name: 'Mila Nule, A.Md.',
          position: 'Koordinator Kondektur',
          role: 'Koordinasi 2 kondektur distribusi',
          email: 'kondektur@ffi-soe.org',
          phone: '+62-821-0000-0019',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Mendukung bongkar muat dan pencatatan serah terima.',
          specialties: ['Dukungan Loading', 'Dokumentasi', 'Kerja Tim'],
          experience: '5 tahun di dukungan distribusi',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
    {
      id: 'OPS-20',
      group: 'operational',
      category: 'Tim Lapangan (1 orang)',
      icon: 'TEAM',
      description: 'Dukungan dan pelaporan di lokasi.',
      members: [
        {
          id: 'OPS-M20',
          name: 'Andri Kofi, S.Sos.',
          position: 'Koordinator Tim Lapangan',
          role: 'Dukungan lokasi & pelaporan',
          email: 'tim.lapangan@ffi-soe.org',
          phone: '+62-821-0000-0020',
          location: 'Soe, Timor Tengah Selatan',
          bio: 'Mengumpulkan umpan balik dan memastikan serah terima di sekolah berjalan lancar.',
          specialties: ['Koordinasi Lapangan', 'Pengumpulan Data', 'Komunikasi'],
          experience: '6 tahun di pemberdayaan masyarakat',
          avatar: '/soe-unit/placeholder-user.jpg',
        },
      ],
    },
  ],
};
